name: Automated Test Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    env:
      Solution_Name: libWindbot.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache nuget
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install Mono
      run: choco install mono --x86

    - name: Install NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r15c

    - name: Reg path
      run: |
        reg add HKCU\Software\Xamarin\VisualStudio\16.0_a5782d1b\Android /v JavaSdkDirectory /d "C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.345-1\x64" /f
        reg add HKCU\Software\Xamarin\VisualStudio\16.0_a5782d1b\Android /v AndroidSdkDirectory /d "C:\Android\android-sdk" /f
        reg add HKCU\Software\Xamarin\VisualStudio\16.0_a5782d1b\Android /v AndroidNdkDirectory /d "C:\hostedtoolcache\windows\ndk\r15c\x64" /f

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    - name: Build!
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=Release

    - name: Test background
      if: ${{ always() }}
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: "2FBurznnoMdzidX11HKbFRy4sw7_317DKBHJWiQsRHbK1xt7w"
        password: "2FBurznno" # You can also put the password in secrets as you wish.
        #foreground: false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: output\libWindbot.aar

    - name: GitHub Release
      #if: github.event_name == 'push'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          output/libWindbot.7z
